query GetAlbum($id: UUID!) {
  album(id: $id) {
    id
    artist
    title
    comments
    year
    firstPlayed {
      ... on FirstPlayedTime {
        timestamp
      }
      ... on FirstPlayedDate {
        year
        month
        day
      }
    }
    sources {
      id
      accurateRip
      comments
      cueIssues
      discs
      download
      edition
      format
      location
      mbid
      tagIssues
    }
  }
}
